<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "easylogin2"
 *
 * Auto generated by Extension Builder 2015-12-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Easylogin',
	'description' => 'Followup of dix_easylogin for TYPO3 7LTS. Use Authentication from facebook, Xing, Google, etc. (everything that uses OAuth or OpenID)',
	'category' => 'plugin',
	'author' => 'Markus Kappe',
	'author_email' => 'markus.kappe@dix.at',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.10.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
